### ISSUE TITLE
endTime().toString() from abstractchapter.h always returns 00:36:00

### ISSUE THREAD

**Issue by SentToDevNull** [Martchus/tagparser#4] opened 2017-05-07 17:31 UTC
I've tested this on a few different matroska files, and although startTime.toString() returns the correct starting times for the chapters, regardless of what file I test, the end time returned for every chapter is 00:36:00.

**Comment by Martchus** [comment] 2017-05-07 17:45
I'm trying to reproduce. However, I've just noticed that none of the official MKV testfiles ("testweave 1") includes chapters. But the end-times of https://belgarath.bunkus.org/mtx-test-data/mkv/handbrake-chapters-2.mkv (from mkvtoolnix testfiles) are displayed correctly in tag editor.

**Comment by Martchus** [comment] 2017-05-07 19:53
I added a test for chapters using the mentioned file and it works: https://github.com/Martchus/tagparser/commit/7747438d94114dd2ce8fd3a816f692edeead1439

But I also found (and fixed) an error in the EBML parser which could cause different issues. So maybe it helps.

If not, could you provide a sample file? Or at least which tool/command you used to create the files which doesn't work?

**Comment by Martchus** [comment] 2017-10-29 17:45
I'm closing because I could not reproduce myself. Just reopen if you can provide further information.

**Closed by Martchus** 2017-10-29 17:45 UTC
Labels: bug
